services:
  dovecot:
    volumes:
      - ./dovecot/99-protocols.conf:/etc/dovecot/conf.d/99-protocols.conf:ro
      - ./dovecot/10-ssl.conf:/etc/dovecot/conf.d/10-ssl.conf:ro
      - ${NGINX_CERTS_DIR:-/root/nginx-proxy/nginx/certs}/${HOST:-mails.nubcoder.com}:/etc/dovecot/ssl:ro
