services:
  dovecot:
    image: dovecot/dovecot
    ports:
      - "1430:143"
      - "9930:993"
      - "1100:110"
      - "9950:995"
    volumes:
      - ./dovecot/99-protocols.conf:/etc/dovecot/conf.d/99-protocols.conf:ro
      - ./dovecot/10-ssl.conf:/etc/dovecot/conf.d/10-ssl.conf:ro
      - ./dovecot/ssl:/etc/dovecot/ssl:ro