# Protocol configuration
protocols = imap pop3 submission lmtp sieve

# IMAP listener on port 143
service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }

  # Brute-force / DoS protection
  process_min_avail = 0
  client_limit = 100
  service_count = 1
}

# POP3 listener on ports 110 and 995
service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }

  # Brute-force / DoS protection
  process_min_avail = 0
  client_limit = 100
  service_count = 1
}
